// import fs from 'node:fs';

export const comedians = [
  {
    id: 1,
    firstName: 'Andrew',
    lastName: 'Schulz',
    age: '39',
    nationality: 'American',
    podcast: 'Flagrant',
    lastSpecial: 'Infamous',
    eventNumber: '4',
    ticketPriceMin: '$30',
    link: '',
  },
  {
    id: 2,
    firstName: 'Iliza',
    lastName: 'Schlesinger',
    age: '39',
    nationality: 'American',
    podcast: 'Truth and Iliza',
    lastSpecial: 'Hot Forever',
    eventNumber: '6',
    ticketPriceMin: '$30',
    link: '',
  },
  {
    id: 3,
    firstName: 'Chris',
    lastName: 'Rock',
    age: '57',
    nationality: 'American',
    podcast: undefined,
    lastSpecial: 'Tamborine',
    eventNumber: '7',
    ticketPriceMin: '$35',
    link: '',
    genres:
      'observational comedy, black comedy, sketch comedy, insult comedy, sarcasm, satire',
  },
  {
    id: 4,
    firstName: 'Russell',
    lastName: 'Peters',
    age: '52',
    nationality: 'Canadian',
    podcast: undefined,
    lastSpecial: 'Act Your Age',
    eventNumber: '12',
    ticketPriceMin: '$45',
    link: '9PihU6Jo7ps',
    genres:
      'insult comedy, heritage comedy, black comedy observational comedy, satire, improvisational comedy',
  },

  {
    id: 5,
    firstName: 'Bill',
    lastName: 'Burr',
    age: '54',
    nationality: 'American',
    podcast: 'Monday Morning',
    lastSpecial: 'Live at Red Rock',
    eventNumber: '3',
    ticketPriceMin: '$45',
    link: '',
  },
];
